# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('expiration_datetime', models.DateTimeField(blank=True, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('email_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='email_manager.EmailInstance')),
            ],
            options={
                'verbose_name': 'Password Reset Code',
                'verbose_name_plural': 'Password Reset Codes',
                'db_table': 'password_reset_code',
            },
        ),
    ]
