# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.apps.staff_member_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_password', models.TextField(blank=True, default=website.apps.staff_member_manager.models.make_random_password)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_staff_members', to='staff_member_manager.StaffMember')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_staff_members', to='staff_member_manager.StaffMember')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_member',
                'verbose_name_plural': 'Staff Members',
                'default_related_name': 'staff_member',
                'verbose_name': 'Staff Member',
            },
        ),
    ]
